### ISSUE TITLE
Add a "show gitignore files" command

### ISSUE THREAD

**Issue by otm** [npx/vscode-hide-gitignored#2]
It would be good to have a "show gitignore files" as well, or a toggle command.

**Comment by AutomateAaron** [comment]
+1 

I think this is a vital feature, it is not obvious how to view files once they're hidden.

**Comment by npx** [comment]
@otm and @AaronNBrock Thank you for your feedback. I'm sorry I only got around to it now, but I just published the new version.

 Let me know if this satisfies your request!
