### ISSUE TITLE
Remove leading slashes from .gitignore patterns in subdirectories

### ISSUE THREAD

**Issue by heavywatal** [npx/vscode-hide-gitignored#3]
Slashes are duplicated when `.gitignore`s in subdirectories are processed. For example, `/config.h` in `src/.gitignore` is translated to `"src//config.h"`, which fails to exclude the file.

**Comment by npx** [comment]
@heavywatal thank you for your feedback!

I just tried it and for me it behaves correctly as follows:
```
src/.gitignore: /config.h  ->  src/config.h
src/.gitignore: config.h   ->  src/**/config.h
```

**Comment by heavywatal** [comment]
Sorry, my bad, I was using [a different extension](https://github.com/stubailo/vscode-ignore-gitignore)! Yours works perfectly!
