### ISSUE TITLE
Commands not found!

### ISSUE THREAD

**Issue by MichZipp** [npx/vscode-hide-gitignored#6]
Hi, 

after installing the extension the command palette is not finding any commands of the extension!
I would love to use this extension.

Looking forward for a reply.

Regards,
Michael

**Comment by npx** [comment]
Hey @MichZipp 

Sorry I might have missed your issue, but I am very confident that this extension is working.
Please make sure you have "hide-gitignored" installed and not "ignore-gitignored"!

Cheers

**Comment by LuisPeregrina** [comment]
@MichZipp can we close this issue?

**Comment by MichZipp** [comment]
@LuisPeregrina Issue can be closed, everything works like expected now!
