### ISSUE TITLE
Files are greyed but not hidden

### ISSUE THREAD

**Issue by jamievicary** [npx/vscode-hide-gitignored#8]
This used to work for me, but now I'm finding my .gitignored files are just greyed, not hidden. Did something change?

**Comment by npx** [comment]
Hey,

nothing has changed!
VSCode added the feature, that .gitignore items are greyed.

This extension does not watch when you are adding more lines to .gitignore, so once .gitignore is updated you need to run the plugin again to make sure it catches that update!

**Comment by jamievicary** [comment]
Hey npx, thanks for your response. I'm afraid it is not clear what it means to "run the plugin again". Looking at the readme, the instruction there is to "run the registered command", which I do not also find clear. (Since this used to work for me, I guess I worked this out in the past, but that memory has not survived to the present.)

**Comment by npx** [comment]
Just run the command "hide gitignored" using the vscode commandline tool (cmd+shift+p) :)

**Comment by jamievicary** [comment]
Thanks Yannick, that works perfectly. You should update your readme to just
say that. It is good standard practice to give clear and explicit
instructions when to do so does not take significantly longer. Thanks for a
great extension.

**Comment by npx** [comment]
Thanks for your feedback!
